---
stages:
  - test
  - release

unit_tests:
  stage: test
  image: image-mirror-prod-registry.cloud.duke.edu/library/golang:1.16
  script:
    - cd planisphere-report-go
    - go test gitlab.oit.duke.edu/devil-ops/planisphere-tools/planisphere-report-go/helpers

coverage:
  stage: test
  script:
    - cd planisphere-report-go
    - go get ./...
    - go test -v gitlab.oit.duke.edu/devil-ops/planisphere-tools/planisphere-report-go/helpers -coverprofile .testCoverage.txt

release:
  stage: release
  image:
    name: goreleaser/goreleaser
    entrypoint: ['']
  services:
    - name: docker:dind
      command: ["--registry-mirror=https://image-mirror-prod-registry.cloud.duke.edu"]
  rules:
    - if: '$CI_COMMIT_TAG =~ /v[0-9]+\.[0-9]+\.[0-9]+/ '
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
  script:
    - cd planisphere-report-go
    - goreleaser release --rm-dist