---
gitlab_urls:
  api: https://gitlab.oit.duke.edu/api/v4/
  download: https://gitlab.oit.duke.edu
release:
  gitlab:
    owner: devil-ops
    name: planisphere-tools
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cli/
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags: >
      -s -w
      -X gitlab.oit.duke.edu/devil-ops/planisphere-tools/planisphere-report-go/cli/cmd.date={{ .CommitTimestamp }}
      -X gitlab.oit.duke.edu/devil-ops/planisphere-tools/planisphere-report-go/cli/cmd.version={{ .Tag }}
      -X gitlab.oit.duke.edu/devil-ops/planisphere-tools/planisphere-report-go/cli/cmd.commit={{ .ShortCommit }}'
    goos:
      - darwin
      - freebsd
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: 'planisphere-report'
archives:
  - format: tar.gz
    name_template: 'planisphere-report-{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      darwin: macOS
checksum:
  name_template: 'planisphere-report-{{ .Version }}_SHA256SUMS'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-snapshot"
changelog:
  skip: true
brews:
  - tap:
      owner: devil-ops
      name: homebrew-devil-ops
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    description: "Planisphere Self Report"
    name: "planisphere-report"
    homepage: "https://gitlab.oit.duke.edu/devil-ops/planisphere-tools/planisphere-report-go"
    install: |
      bin.install "planisphere-report"
    plist: |
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
          <key>Label</key>
          <string>com.duke.planisphere.report</string>
          <key>ProgramArguments</key>
          <array>
              <string>/usr/local/bin/planisphere-report</string>
              <string>report</string>
          </array>
          <key>RunAtLoad</key>
          <true/>
          <key>StandardOutPath</key>
          <string>/usr/local/var/log/planisphere-report.log</string>
          <key>StandardErrorPath</key>
          <string>/usr/local/var/log/planisphere-report.err</string>
          <key>StartInterval</key>
          <integer>3600</integer>
      </dict>
      </plist>
    caveats: |
      Please make sure to update your configuration file with your Planisphere
      Self Report Key and any overrides or extra data before (re)starting the
      service (via sudo launchctl or by restarting your computer):
      
          sudo vi /etc/planisphere-report.yaml
          sudo launchctl unload /Library/LaunchDaemons/com.duke.planisphere.report.plist
          sudo launchctl load /Library/LaunchDaemons/com.duke.planisphere.report.plist

      Log files are available at
          /var/log/planisphere-report.log
      and
          /var/log/planisphere-report.err
nfpms:
  - id: packages
    bindir: /usr/bin
    package_name: planisphere-report
    maintainer: Drew Stinnett <drew.stinnett@duke.edu>
    formats:
      - deb
      - rpm
      - apk
    contents:
      - src: packaging/systemd/planisphere-report.service
        dst: /usr/lib/systemd/system/planisphere-report.service
      - src: packaging/systemd/planisphere-report.timer
        dst: /usr/lib/systemd/system/planisphere-report.timer
    scripts:
      postinstall: "packaging/scripts/postinstall.sh"
      preremove: "packaging/scripts/preremove.sh"
      postremove: "packaging/scripts/postremove.sh"